import Head from "next/head";
import MainLayout from "../src/components/layout/mainLayout";
import Footer from "../src/components/layout/footer";
import UserTableContainer from "../src/components/containers/usertableContainer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fidem task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <main>
          <UserTableContainer />
        </main>
        <Footer />
      </MainLayout>
    </div>
  );
}
